spring:
  datasource:
    url: jdbc:mariadb://172.17.0.1:3306/app10_prod?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: 220808
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    com.ll.exam.app10.app: info
custom:
  genFileDirPath: /gen